name: 空白 Issue | Blank Issue
description:
  一个空白的 issue 模板。
  A blank issue template.
labels: ["status: needs triage"]
body:
  - type: textarea
    id: comment
    attributes:
      label: 详细内容 Details